# site settings
title: Diogo Silva
subtitle: by HTML5 UP
email: emiliofast@tutanota.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://el-paquete.github.io" # the base hostname & protocol for your site
author: Diogo Silva
street_address: Avenida das Flores
city: Braga
state:
zip_code:
country: Portugal
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/diogo-costa-silva
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/diogo-costa-silva
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
